"""Types for the part of gmpy2 the project uses: mpq, and the mpz it rounds to.

gmpy2 ships no types. Arithmetic is typed with mpq and whole numbers only:
an mpq combined with a float gives an inexact mpfr, so a float must be
made an mpq first. Comparisons with a float are exact, and are allowed.
"""

from typing import overload

class mpz:
    """A GMP integer; not an int, so int() makes one."""

    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __abs__(self) -> mpz: ...
    def __neg__(self) -> mpz: ...
    def __add__(self, other: mpz | int, /) -> mpz: ...
    def __radd__(self, other: mpz | int, /) -> mpz: ...
    def __sub__(self, other: mpz | int, /) -> mpz: ...
    def __rsub__(self, other: mpz | int, /) -> mpz: ...
    def __mul__(self, other: mpz | int, /) -> mpz: ...
    def __rmul__(self, other: mpz | int, /) -> mpz: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __lt__(self, other: mpz | int, /) -> bool: ...
    def __le__(self, other: mpz | int, /) -> bool: ...
    def __gt__(self, other: mpz | int, /) -> bool: ...
    def __ge__(self, other: mpz | int, /) -> bool: ...
    def __hash__(self) -> int: ...

class mpq:
    """An exact rational number, always in lowest terms."""

    @overload
    def __new__(cls, value: mpq | int | float = ..., /) -> mpq: ...
    @overload
    def __new__(cls, numerator: int, denominator: int, /) -> mpq: ...
    @property
    def numerator(self) -> mpz: ...
    @property
    def denominator(self) -> mpz: ...
    def __add__(self, other: mpq | int, /) -> mpq: ...
    def __radd__(self, other: mpq | int, /) -> mpq: ...
    def __sub__(self, other: mpq | int, /) -> mpq: ...
    def __rsub__(self, other: mpq | int, /) -> mpq: ...
    def __mul__(self, other: mpq | int, /) -> mpq: ...
    def __rmul__(self, other: mpq | int, /) -> mpq: ...
    def __truediv__(self, other: mpq | int, /) -> mpq: ...
    def __rtruediv__(self, other: mpq | int, /) -> mpq: ...
    def __neg__(self) -> mpq: ...
    def __pos__(self) -> mpq: ...
    def __abs__(self) -> mpq: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __lt__(self, other: mpq | int | float, /) -> bool: ...
    def __le__(self, other: mpq | int | float, /) -> bool: ...
    def __gt__(self, other: mpq | int | float, /) -> bool: ...
    def __ge__(self, other: mpq | int | float, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def as_integer_ratio(self) -> tuple[mpz, mpz]: ...
    def __float__(self) -> float: ...
    def __int__(self) -> int: ...
    @overload
    def __round__(self) -> mpz: ...
    @overload
    def __round__(self, ndigits: int, /) -> mpq: ...
